[package]
name = "iref"
version = "2.2.3"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2021"
categories = ["web-programming", "internationalization"]
keywords = ["iri", "uri", "resource", "identifier", "slice"]
description = "Internationalized Resource Identifiers (IRIs) and References, borrowed and owned."
repository = "https://github.com/timothee-haudebourg/iref"
documentation = "https://docs.rs/iref"
license = "MIT/Apache-2.0"
readme = "README.md"

[features]
default = []
ignore-grammars = []

[dependencies]
pct-str = "2.0"
smallvec = "1.2"
serde = { version = "1.0", optional = true }
hashbrown = { version = "0.14.0", optional = true }
thiserror = "1.0.40"
static-regular-grammar = { git = "https://github.com/timothee-haudebourg/static-regular-grammar.git" }

[dev-dependencies]
serde_json = "1.0"

[[example]]
name = "serde"
required-features = [ "serde", "serde/derive" ]